const gifs = import.meta.glob("./assets/exercises/*.gif", { eager: true });
const getGif = (name) => gifs[`./assets/exercises/${name}`]?.default;

// ─── EXERCISE DATABASE ───────────────────────────────────────────────
export const MUSCLE_GROUPS = [
  { id: "chest",     label: "Chest",     color: "#ef4444", glow: "rgba(239,68,68,0.4)"  },
  { id: "back",      label: "Back",      color: "#3b82f6", glow: "rgba(59,130,246,0.4)" },
  { id: "shoulders", label: "Shoulders", color: "#8b5cf6", glow: "rgba(139,92,246,0.4)" },
  { id: "arms",      label: "Arms",      color: "#00e5ff", glow: "rgba(0,229,255,0.4)"  },
  { id: "core",      label: "Core",      color: "#f59e0b", glow: "rgba(245,158,11,0.4)" },
  { id: "legs",      label: "Legs",      color: "#10b981", glow: "rgba(16,185,129,0.4)" },
];

// gender: "male" | "female" | "both"
export const EXERCISES = [

  // ════════════════════════════════════════════════════════════════
  // MALE EXERCISES
  // ════════════════════════════════════════════════════════════════

  // ── CHEST ──────────────────────────────────────────────────────
  {
    id: "m-pushup",
    gender: "male",
    muscle: "chest",
    name: "Push-Up",
    sets: 3, reps: "12–15",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("Push-Up.gif"),
    cues: [
      "Hands shoulder-width apart, wrists under shoulders",
      "Keep body in a straight plank line",
      "Lower chest to 1 inch off the floor",
      "Push back up, fully extend arms",
    ],
    muscles: ["Pectorals", "Triceps", "Front Deltoids"],
    hasTracker: false,
  },
  {
    id: "m-incline-pushup",
    gender: "male",
    muscle: "chest",
    name: "Incline Push-Up",
    sets: 3, reps: "15–20",
    difficulty: "Beginner",
    equipment: "Bench / Chair",
    gif: getGif("Incline-Push-Up.gif"),
    cues: [
      "Place hands on elevated surface",
      "Body straight from head to heels",
      "Lower chest toward the surface",
      "Drive back up through your palms",
    ],
    muscles: ["Upper Chest", "Triceps", "Shoulders"],
    hasTracker: false,
  },

  // ── BACK ────────────────────────────────────────────────────────
  {
    id: "m-deadlift",
    gender: "male",
    muscle: "back",
    name: "Deadlift",
    sets: 4, reps: "8–10",
    difficulty: "Intermediate",
    equipment: "Barbell",
    gif: getGif("Barbell-Deadlift.gif"),
    cues: [
      "Stand with feet hip-width apart, bar over mid-foot",
      "Hinge at hips, grip bar just outside legs",
      "Chest up, back flat — brace your core",
      "Drive through heels, hips and shoulders rise together",
    ],
    muscles: ["Erector Spinae", "Glutes", "Hamstrings", "Traps"],
    hasTracker: true,
    trackerId: "deadlift",
  },
  {
    id: "m-pull-up",
    gender: "male",
    muscle: "back",
    name: "Pull-Up",
    sets: 3, reps: "6–10",
    difficulty: "Intermediate",
    equipment: "Pull-up Bar",
    gif: getGif("Pull-up.gif"),
    cues: [
      "Hang from bar with full arm extension",
      "Pull elbows down and back to raise yourself",
      "Chin clears the bar at the top",
      "Lower slowly — control the negative",
    ],
    muscles: ["Latissimus Dorsi", "Biceps", "Rear Deltoids"],
    hasTracker: false,
  },

  // ── SHOULDERS ───────────────────────────────────────────────────
  {
    id: "m-shoulder-press",
    gender: "male",
    muscle: "shoulders",
    name: "Shoulder Press",
    sets: 3, reps: "10–12",
    difficulty: "Intermediate",
    equipment: "Dumbbells",
    gif: getGif("Dumbbell-Shoulder-Press.gif"),
    cues: [
      "Sit or stand, dumbbells at shoulder height",
      "Palms facing forward, elbows at 90°",
      "Press straight up until arms are almost locked",
      "Lower slowly back to start — control the descent",
    ],
    muscles: ["Deltoids", "Triceps", "Upper Traps"],
    hasTracker: false,
  },
  {
    id: "m-lateral-raise",
    gender: "male",
    muscle: "shoulders",
    name: "Lateral Raise",
    sets: 3, reps: "12–15",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    gif: getGif("Dumbbell-Lateral-Raise.gif"),
    cues: [
      "Stand with dumbbells at sides, slight knee bend",
      "Raise arms out to the side to shoulder height",
      "Lead with elbows, slight forward tilt",
      "Lower slowly — don't let gravity do the work",
    ],
    muscles: ["Medial Deltoids", "Supraspinatus"],
    hasTracker: false,
  },

  // ── ARMS ────────────────────────────────────────────────────────
  {
    id: "m-bicep",
    gender: "male",
    muscle: "arms",
    name: "Bicep Curl",
    sets: 3, reps: "10–12",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    gif: getGif("Dumbbell-Curl.gif"),
    cues: [
      "Stand tall, dumbbells at sides, palms forward",
      "Keep elbows pinned close to your torso",
      "Curl up to shoulder level, squeeze at top",
      "Lower slowly — full extension at the bottom",
    ],
    muscles: ["Biceps Brachii", "Brachialis", "Forearms"],
    hasTracker: true,
    trackerId: "bicep",
  },
  {
    id: "m-tricep-dip",
    gender: "male",
    muscle: "arms",
    name: "Tricep Dip",
    sets: 3, reps: "12–15",
    difficulty: "Beginner",
    equipment: "Parallel Bars / Bench",
    gif: getGif("Triceps-Dips.gif"),
    cues: [
      "Grip edge of bench, fingers pointing forward",
      "Legs extended straight out in front",
      "Lower body by bending elbows to 90°",
      "Press back up, squeezing triceps at the top",
    ],
    muscles: ["Triceps", "Chest", "Front Deltoids"],
    hasTracker: false,
  },

  // ── CORE ────────────────────────────────────────────────────────
  {
    id: "m-plank",
    gender: "male",
    muscle: "core",
    name: "Plank",
    sets: 3, reps: "30–60 sec",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("body-saw-plank.gif"),
    cues: [
      "Forearms on floor, elbows under shoulders",
      "Body forms a straight line head to heels",
      "Squeeze core, glutes, and quads throughout",
      "Don't let hips sag or pike upward",
    ],
    muscles: ["Transverse Abdominis", "Obliques", "Glutes"],
    hasTracker: false,
  },
  {
    id: "m-crunch",
    gender: "male",
    muscle: "core",
    name: "Crunch",
    sets: 3, reps: "20–25",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("Male-Crunch.gif"),
    cues: [
      "Lie on back, knees bent, feet flat",
      "Fingertips lightly behind ears — don't pull neck",
      "Exhale and curl shoulders off the floor",
      "Lower with control, don't drop back down",
    ],
    muscles: ["Rectus Abdominis", "Hip Flexors"],
    hasTracker: false,
  },

  // ── LEGS ────────────────────────────────────────────────────────
  {
    id: "m-squat",
    gender: "male",
    muscle: "legs",
    name: "Squat",
    sets: 4, reps: "12–15",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("squat.gif"),
    cues: [
      "Feet shoulder-width apart, toes slightly out",
      "Chest up, core braced, gaze forward",
      "Push knees out in line with toes as you descend",
      "Drive through heels to stand — fully extend at top",
    ],
    muscles: ["Quadriceps", "Glutes", "Hamstrings", "Calves"],
    hasTracker: false,
  },
  {
    id: "m-lunge",
    gender: "male",
    muscle: "legs",
    name: "Lunge",
    sets: 3, reps: "10 each leg",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("lunge.gif"),
    cues: [
      "Stand tall, step one foot forward",
      "Lower back knee toward the floor — don't touch",
      "Front knee stays behind front toes",
      "Push through front heel to return to start",
    ],
    muscles: ["Quadriceps", "Glutes", "Hamstrings"],
    hasTracker: false,
  },

  // ════════════════════════════════════════════════════════════════
  // FEMALE EXERCISES
  // ════════════════════════════════════════════════════════════════

  // ── CHEST ──────────────────────────────────────────────────────
  {
    id: "f-kneeling-pushup",
    gender: "female",
    muscle: "chest",
    name: "Kneeling Push-Up",
    sets: 3, reps: "12–15",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("female-Kneeling-Push-up.gif"),
    cues: [
      "Knees on floor, hands shoulder-width apart",
      "Keep hips down — body straight from knee to head",
      "Lower chest to 1 inch off the floor",
      "Push back up, fully extend arms",
    ],
    muscles: ["Pectorals", "Triceps", "Front Deltoids"],
    hasTracker: false,
  },
  {
    id: "f-incline-bench-press",
    gender: "female",
    muscle: "chest",
    name: "Incline Barbell Bench Press",
    sets: 3, reps: "15–20",
    difficulty: "Beginner",
    equipment: "Incline Bench",
    gif: getGif("female-Incline-Barbell-Bench-Press.gif"),
    cues: [
      "Set bench to 30–45° incline",
      "Grip bar slightly wider than shoulders",
      "Lower bar to upper chest with control",
      "Drive back up through your palms",
    ],
    muscles: ["Upper Chest", "Triceps", "Shoulders"],
    hasTracker: false,
  },

  // ── BACK ────────────────────────────────────────────────────────
  {
    id: "f-deadlift",
    gender: "female",
    muscle: "back",
    name: "Deadlift",
    sets: 4, reps: "8–10",
    difficulty: "Intermediate",
    equipment: "Barbell",
    gif: getGif("female-Barbell-Deadlift.gif"),
    cues: [
      "Stand with feet hip-width apart, bar over mid-foot",
      "Hinge at hips, grip bar just outside legs",
      "Chest up, back flat — brace your core",
      "Drive through heels, hips and shoulders rise together",
    ],
    muscles: ["Erector Spinae", "Glutes", "Hamstrings", "Traps"],
    hasTracker: true,
    trackerId: "deadlift",
  },
  {
    id: "f-pull-up",
    gender: "female",
    muscle: "back",
    name: "Top Half Pull-Up",
    sets: 3, reps: "6–10",
    difficulty: "Intermediate",
    equipment: "Pull-up Bar",
    gif: getGif("female-Top-Half-Pull-up.gif"),
    cues: [
      "Hang from bar with full arm extension",
      "Pull elbows down and back to raise yourself",
      "Chin clears the bar at the top",
      "Lower slowly — control the negative",
    ],
    muscles: ["Latissimus Dorsi", "Biceps", "Rear Deltoids"],
    hasTracker: false,
  },

  // ── SHOULDERS ───────────────────────────────────────────────────
  {
    id: "f-shoulder-press",
    gender: "female",
    muscle: "shoulders",
    name: "Resistance Band Seated Shoulder Press",
    sets: 3, reps: "10–12",
    difficulty: "Intermediate",
    equipment: "Resistance Band",
    gif: getGif("female-Resistance-Band-Seated-Shoulder-Press.gif"),
    cues: [
      "Sit or stand, dumbbells at shoulder height",
      "Palms facing forward, elbows at 90°",
      "Press straight up until arms are almost locked",
      "Lower slowly back to start — control the descent",
    ],
    muscles: ["Deltoids", "Triceps", "Upper Traps"],
    hasTracker: false,
  },
  {
    id: "f-lateral-raise",
    gender: "female",
    muscle: "shoulders",
    name: "Leaningg Single Arm Dumbell Lateral Raise",
    sets: 3, reps: "12–15",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    gif: getGif("female-Leaning-Single-Arm-Dumbbell-Lateral-Raise.gif"),
    cues: [
      "Stand with dumbbells at sides, slight knee bend",
      "Raise arms out to the side to shoulder height",
      "Lead with elbows, slight forward tilt",
      "Lower slowly — don't let gravity do the work",
    ],
    muscles: ["Medial Deltoids", "Supraspinatus"],
    hasTracker: false,
  },

  // ── ARMS ────────────────────────────────────────────────────────
  {
    id: "f-bicep",
    gender: "female",
    muscle: "arms",
    name: "Seated-Bicep Curl",
    sets: 3, reps: "10–12",
    difficulty: "Beginner",
    equipment: "Dumbbells",
    gif: getGif("female-seated-biceps-curl.gif"),
    cues: [
      "Stand tall, dumbbells at sides, palms forward",
      "Keep elbows pinned close to your torso",
      "Curl up to shoulder level, squeeze at top",
      "Lower slowly — full extension at the bottom",
    ],
    muscles: ["Biceps Brachii", "Brachialis", "Forearms"],
    hasTracker: true,
    trackerId: "bicep",
  },
  {
    id: "f-tricep-dip",
    gender: "female",
    muscle: "arms",
    name: "Cable-Rope-Overhead-Triceps-Extension",
    sets: 3, reps: "12–15",
    difficulty: "Beginner",
    equipment: "Cable Machine",
    gif: getGif("female-Cable-Rope-Overhead-Triceps-Extension.gif"),
    cues: [
      "Grip edge of bench, fingers pointing forward",
      "Legs extended straight out in front",
      "Lower body by bending elbows to 90°",
      "Press back up, squeezing triceps at the top",
    ],
    muscles: ["Triceps", "Chest", "Front Deltoids"],
    hasTracker: false,
  },

  // ── CORE ────────────────────────────────────────────────────────
  {
    id: "f-plank",
    gender: "female",
    muscle: "core",
    name: "Spiderman Plank",
    sets: 3, reps: "30–60 sec",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("female-spiderman-plank.gif"),
    cues: [
      "Forearms on floor, elbows under shoulders",
      "Body forms a straight line head to heels",
      "Squeeze core, glutes, and quads throughout",
      "Don't let hips sag or pike upward",
    ],
    muscles: ["Transverse Abdominis", "Obliques", "Glutes"],
    hasTracker: false,
  },
  {
    id: "f-crunch",
    gender: "female",
    muscle: "core",
    name: "Crunch",
    sets: 3, reps: "20–25",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("Crunch.gif"),
    cues: [
      "Lie on back, knees bent, feet flat",
      "Fingertips lightly behind ears — don't pull neck",
      "Exhale and curl shoulders off the floor",
      "Lower with control, don't drop back down",
    ],
    muscles: ["Rectus Abdominis", "Hip Flexors"],
    hasTracker: false,
  },

  // ── LEGS ────────────────────────────────────────────────────────
  {
    id: "f-squat",
    gender: "female",
    muscle: "legs",
    name: "Jump Squat",
    sets: 4, reps: "12–15",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("female-Jump-Squat.gif"),
    cues: [
      "Feet shoulder-width apart, toes slightly out",
      "Chest up, core braced, gaze forward",
      "Push knees out in line with toes as you descend",
      "Drive through heels to stand — fully extend at top",
    ],
    muscles: ["Quadriceps", "Glutes", "Hamstrings", "Calves"],
    hasTracker: false,
  },
  {
    id: "f-lunge",
    gender: "female",
    muscle: "legs",
    name: "Curtsy Lunge",
    sets: 3, reps: "10 each leg",
    difficulty: "Beginner",
    equipment: "Bodyweight",
    gif: getGif("female-curtsy-lunge.gif"),
    cues: [
      "Stand tall, step one foot forward",
      "Lower back knee toward the floor — don't touch",
      "Front knee stays behind front toes",
      "Push through front heel to return to start",
    ],
    muscles: ["Quadriceps", "Glutes", "Hamstrings"],
    hasTracker: false,
  },
];